config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'pages#about', as: :about
  get 'contact', to: 'pages#contact', as: :contact

  root to: 'pages#home'
  resources :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :first_name, presence: {message: "Provide your name"}
  validate :phone_or_email_required
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i

  def phone_or_email_required
    if !phone.present? && !email.present?
      errors.add(:phone, "Add either phone or email")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  # GET /contacts
  # GET /contacts.json



  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])
  end

  # GET /contacts/new
  def new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      ContactMailer.request2(@contact).deliver_now
    end

    respond_to do |format|
      if @contact.save
        format.html { redirect_to root_path, notice: "Your message has been sent, We'll be in contact soon" }
      else
        format.html { render "pages/contact" }
      end
    end

    # if @contact.deliver
    #   flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    # else
    #   flash.now[:error] = 'Cannot send message.'
    #   render :new
    # end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :phone, :email, :message, :preference, :subject)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def contact
    @contact = Contact.new
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <meta name="description" content="Denver Pool Management: Full Commercial Pool Management">
    <meta name="keywords" content="Denver,Pool,Cleaning,Management,Company">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <title>Denver Pools</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render "shared/footer" %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="banner" , style="background-image: url(<%= image_path("mountain-pool.jpg")%> );">
  <div class="banner-content">
    <h1>About</h1>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="banner", id="contact-banner", style="background-image: url(<%= image_path("water.jpg")%> );">
  <div class="banner_content_contact" id= "contact_heading">
    <h1>Contact Us</h1>
    <h3 class="call-now">Phone:</h3>
    <a href="tel:3033458423" class="contact-phone"> 303-345-8423</a>
    <p>Or fill out this form and we'll be in touch soon:</p>
    <div class="form-box">
      <%= simple_form_for @contact do |f| %>
        <%= f.error_notification %>
        <%= f.input :first_name, label: "First Name", placeholder: "First Name" %>
        <%= f.input :last_name, label: "Last Name", placeholder: "Last Name"%>
        <%= f.input :phone, placeholder: "303-###-####" %>
        <%= f.input :email, placeholder: "hello@mail.com"  %>
        <%= f.input :preference, label: "Preferred Form of Contact:",  priority: [ "Email" ], collection: [ "Phone Call", "Email", "Text Message", "Any"] %>
        <%= f.input :subject, label: "I'm inquiring for:",  priority: [ "Email" ], as: :radio_buttons, collection: [ "Service Quote", "Repair Quote", "Other"], class: 'radio-btn' %>
        <%= f.input :message, as: :text, placeholder: "What would like help with, best time to contact you, special requests, or anything else you think we should know." %>

          <div>
            </br>
            <div class="form-actions">
              <%= f.submit :submit, value: "SUBMIT", id: "submit-btn", class: 'btn' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" , style="background-image: url(<%= image_path("pool.jpg")%> );">
  <div class="banner-content">
    <h1>Denver Pool Management</h1>
    <a href="tel:3033458423" id="phone-num" style="text-decoration: none;">(303) 345-8423</a>
    <%= link_to "REQUEST AN ESTIMATE", contact_path, class: "btn", id: "home-btn"%>
  </div>
</div>

<div class="first-box">
  <h3>Who We Are</h3>
  <p>Simply put, this is what commercial pool service should always be. Denver Pool Management prides itself on superior customer service and communication, a commitment to ethical practices, and detail-oriented work. DPM is a full-service commercial swimming pool management company, providing services ranging from basic pool maintenance (balancing chemicals, debris removal) and equipment repairs – to on-site staffing of lifeguards and monitors – to large scale repairs, remodels and new builds. And regardless of the scope of work, DPM prides itself on its customer-friendly approach!</p>
</div>

<div class="banner" , id="services-image", style="background-image: url(<%= image_path("feet.jpg")%> );">

  <div class="banner-box", id= "services-box">
    <h3>Services</h3>
    <p>Full commercial pool management, including:</p>
    <ul>
      <li>Service, basic maintenance and chemical supply</li>
      <li>Small-scale repairs and equipment upgrades</li>
      <li>Lifeguards and monitors</li>
      <li>Equipment room rebuilds, structural repairs and remodels, and new build design and construction</li>
    </ul>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
    <a href="tel:3033458423" class="foot-phone"> Phone: 303-345-8423</a>
  </div>
  <%= link_to "http://www.amyhogue.com/",  target: :_blank do %>
    <div class="yam-footer">
      <p>Powered By</p>
      <%= image_tag("yam.png")%>
      <p>Yam</p>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-pool">
  <!-- Logo -->

  <div class="title">
    <%= link_to root_path, class: "navbar-pool-brand" do %>
    <% end %>
    <%= link_to "Denver Pool", root_path, id: "title-name" %>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-pool-right hidden-xs hidden-sm">
    <a class="navbar-pool-item navbar-pool-link" href="/#services-box" >Services </a>
    <%= link_to "Contact", contact_path, class: "navbar-pool-item navbar-pool-link" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-pool-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-pool-dropdown-menu">
        <li><a href="/#services-box" >Services</a></li>
          <li>
          <%= link_to "Contact Us", contact_path %>
        </li>
      </ul>
    </div>
  </div>
</div>